### PR TITLE
DlgPoly

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by Lunalo** [comment]
@stevenndungu 

I think you should close one to avoid confusion

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers This is ready for review.
Note: Default radio button is orthogonal for now but ought to be Simple I guess (unless othws). This is to be addressed later on with @dannyparsons on issue to do with reading of code by the new system. 

Review can be done on the general functionality of the dialogue and of course code structure which will not change with the above mentioned adjustment. Thanks
Steven

**Comment by stevenndungu** [comment]
Just a minute I fix a small bug

**Comment by stevenndungu** [comment]
Fixed the issue, this is ready now

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers this is ready for re-view

**Comment by dannyparsons** [comment]
this is being merged because it has changes on the core needed for other dialogs. However, someone should still review this dialog.

**Comment by lilyclements** [comment]
I am going to review this dialog now/make small changes. @stevenndungu are you still working on this?

**Comment by stevenndungu** [comment]
Not working on it. Review it, in case of any bug report here I will create a branch to fix issues raised (I there is any) since I deleted the branch that I was working on.

**Comment by lilyclements** [comment]
Great, I have made minor edits. There is one or two bugs. I want to discuss one of them in case it is intentional so I would like to know the reasons behind it! The other bug is that the reset doesn't reset. I'm fixing the latter now and we can discuss the former shortly

**Comment by stevenndungu** [comment]
Okay, am happy to discuss.

**Comment by lilyclements** [comment]
Great, I'll send it to the main AMI/Instat and we can discuss

**Pull request merged**
