### PR TITLE
PICSA dialogs

### PR DESCRIPTION
**Pull request by Lunalo**
Hi @africanmathsinitiative/instat , 

After Discussion with @stevekogo  yesterday I got an idea on how PICSA dialogs can look like.

I have done initial designs and everybody is welcome to the discussions since we need to improve on it after which we will implement the dialogs.

Thanks.

### CODE REVIEW

**Comment by rdstern** [comment]
Just to add that I am currently with Francis, who has been working on an R function for the crops work.  I will be discussing with him later today and can send some information then.

**Comment by lilyclements** [comment]
So , I have had a look at them. I do not know much about what climatic options we can do by R so perhaps this comment is redundant.
My immediate thoughts are that I like either having three separate dialogs, or it all together in one. 

Some comments on All-in-One:
- It depends what we plan to go into "Crop Models" on the PICSA dialog. It could look strange if when we have "Rainfall" or "Temperature" selected on the PICSA dialog to have the big gap (since presumably grpCropModel would be not visible in this case). However, it could be moved to cover "Threshold Value" and "grpPlots" potentially?
- It is nice to have it all in one, however, as it can show the similarities between the three options.
- Out of interest, is it going to be that the user can select any variable and automatically the system will bring up options related to that variable. (e.g., they happen to select a rainfall variable and the plot options for rainfall come up without the user having to explicity type in the top they want to do Rainfall?)
- However, the user could pick their options for, say, Rainfall.
Then they run the plot but still wish to keep those options selected on the dialog for Rainfall for whatever reason! (perhaps they want to come back to it with another variable later on)
They then reopen the dialog to change their options for Temperature, decide they want to refresh their options on Temperature. Then they've lost their options they selected for Rainfall? I know it's not that loads of options could be altered but just something to think about I guess.
- How would the help buttons work with all three together in one? Do we plan to just have one PICSA "help" option anyway?

**Comment by dannyparsons** [comment]
@Lunalo can you provide screen shots of each dialog, maybe in a small document with a little description of key parts? I think that would be useful for everyone. 
I don't think they need to be included in the code yet, unless there are particular features you think need to be seen in the software instead of screen shots.

**Comment by lilyclements** [comment]
@Lunalo @dannyparsons can this be closed?
My understanding was that this was just to show dialog designs rather than for it to be merged in?

**Pull request closed without merging**
