### PR TITLE
Splidate edit

### PR DESCRIPTION
**Pull request by Lunalo**
Hi @africanmathsinitiative/instat 

You are welcome to review the code. @stevenndungu  and I have updated the method to accommodate changes suggested by @rdstern .

Thanks.

### CODE REVIEW

**Comment by FrancoisJRenaud** [comment]
@africanmathsinitiative/instat Sorry for the mass message... It's about commenting again... Thanks @rdstern  for your suggestion (comment) of this morning's skype call...  

Commenting also applies to R methods (this pull request is about split_date method). I would love to review your work if @Lunalo and @stevenndungu you could give me (and future users/contributors/people working on the documentation/employers...) some explanations inline about what you have been adding to the project. Otherwise it takes me a lot of time to figure out what you are doing, especially since I am not familiar with the R syntax. We can go over it orally first if it helps.

I recommend to explain what each of the sub/functions you are adding is doing, what are it's different parameters for, maybe how/where these are set, so maybe roughly where is the sub/function called from, for what purpose, at what stage in the whole process of the running software... 

Doesn't need to be long, just enlightening. Details are not necessary as long as the ideas are clear. Doesn't need to be very technical, but it does need to be accurate... 

If you feel you need to write too much at one place to explain what's happening there, maybe it is worth commenting other bits of the software that are used in your edits, and rely on/refer to these explanations. It is better to spread out explanations slightly. Good to document the definitions and declarations instead of commenting each call of a function/sub/class. The first reflex when facing a mysterious object would be to go to the definition, and read the comments explaining the definition. I know this is sometimes difficult as you don't want to edit too many different files...

Hopefully this helps. I m happy to review/help with any commenting...

Cheers, 
François

**Comment by rdstern** [comment]
Is this a discussion on the Organise > Column: Date > Use Date dialogue.  If so, then that is one that I would really like to see working for next week.  It illustrates another point for our climatic discussions then, namely that some aspects from the climatic menu in the original Instat are now in the main menu in this version.

**Comment by Lunalo** [comment]
Hi @stevekogo ,

Can you review this please

**Comment by Lunalo** [comment]
@FrancoisJRenaud 

Thanks for the idea. I will Start commenting every time I do R methods.

We can go through the whole method this morning .

Thanks

**Comment by FrancoisJRenaud** [comment]
So we have added a comment to explain split date method with @Lunalo. Also did some testing together and suggested a small change about the order of the if statements (which determines the order in which columns are created in the data). After this will have been edited, I think the pull request is ready for @dannyparsons.

**Pull request merged**
