### PR TITLE
climatic methods Menus

### PR DESCRIPTION
**Pull request by aduut**
Modified Is NA List with all its parameters.

### CODE REVIEW

**Comment by volloholic** [comment]
Please finish writing the code required for both dialogues so that we can complete the merge. In the future seperate out each dialogue as a separate pull request

**Comment by aduut** [comment]
The power was out that's why I did those commits my battery is broken so I
it has less then an hour before it dies.

**Comment by volloholic** [comment]
Committing is fine but sending a pull request should be done on completion.

Dr David Stern
Mathematical Scientist
Statistical Services Centre | University of Reading | PO Box 240 | RG6 6FN | United Kingdom
• +44 (0)118 378 7964| • www.reading.ac.uk/ssc<http://www.reading.ac.uk/ssc> | •  d.a.stern@reading.ac.uk<mailto:d.a.stern@reading.ac.uk>  | [cid:image004.jpg@01D08367.691C8010]  volloholic
Vice-President | International Association for Statistical Education  | (iase-web.org<http://iase-web.org/>)


Further information:  Statistical Support & Consultancy<http://www.reading.ac.uk/ssc/consultancy> | Statistical Training<http://www.reading.ac.uk/ssc/training> |About us<http://www.reading.ac.uk/ssc/aboutus/> | Visiting us?<http://www.reading.ac.uk/ssc/contact.php>

Follow us on:  [cid:image001.png@01D0832F.38FADA90] <https://twitter.com/SSCReadingUK>   [cid:image002.png@01D0832F.38FADA90] <https://plus.google.com/u/1/b/101034923032392019689/101034923032392019689/posts>   [cid:image003.png@01D0832F.38FADA90] <https://www.youtube.com/user/SSCbroadcast>

**Comment by aduut** [comment]
Yes, true, many thanks.

**Comment by maxwellfundi** [comment]
This is redone, it could be closed now. 
Thanks

**Pull request closed without merging**
