### PR TITLE
dlgDuplicateColumns

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers This is ready for review

Changes made:
- Bug fix. It was reading in the name of the column not the contents
- Updated some of the code in the SetDefaults sub
- Bug fix. ucrInputColumnName only has a name once something has been inputted in the receiver, so there was a developer error upon opening the dialog when nothing was in the receiver.

### CODE REVIEW

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers Duplicate Columns is fixing a bug and developer error. This needs to be reviewed so it can go into tomorrow's version.

**Comment by lilyclements** [comment]
Perhaps if I ask in Kiswahili: @africanmathsinitiative/developers Hii ni tayari kwa ajili ya mapitio
(according to google translate that's meant to say "This is ready for review")

**Comment by Lunalo** [comment]
@lilyclements 

it is "Hii iko tayari kwa ukaguzi"

I will review it soon

**Comment by lilyclements** [comment]
Asante!

**Comment by Lunalo** [comment]
The dialog is working fine. You only need to the right spacing on the design

**Comment by Lunalo** [comment]
One question for @rdstern  @dannyparsons 

If we duplicate column do we generate or calculate ?

I think it should be generate

**Comment by Lunalo** [comment]
When I change the radio button. The content in the receiver is shaking. We may want to look at why this is happening

**Comment by lilyclements** [comment]
The content in the receiver does not do this to me, are you doing this on the most updated branch out of interest?

**Comment by Lunalo** [comment]
Yes, I thinking writing up as an issue will be a good idea

**Comment by lilyclements** [comment]
Great, I'll write up an issue on that. Other than that, @Lunalo I have made the necessary changes and this is ready for a re-review.

I have also tried this on the most updated branch and I don't see the shaking. Perhaps if you update your branch and still get this issue, we could skype and you could show it to me?

**Comment by stevekogo** [comment]
It seems this is almost ready. @Lunalo can clarify the state of this.

**Comment by Lunalo** [comment]
Okay. I will test it again and provide the feedback

**Comment by Lunalo** [comment]
@dannyparsons 

This is ready

**Pull request merged**
