### PR TITLE
dlg protect

### PR DESCRIPTION
**Pull request by aduut**
Request created on 26.05.2016

### CODE REVIEW

**Comment by aduut** [comment]
Some conflicts here.

**Comment by dannyparsons** [comment]
Hi Abib, I can see you have made good progress on the protect dialog but as you noticed there are conflicts because of all the extra files you have changed.
I suggest you go through the changes carefully and see which ones you can fix easily. For example, you have created a file called Form1, this can just be deleted. It also seems you made a new project called dlgProtect.
In future, always look at changes being send when you do a commit. In the commit window it shows what changes you have made and there is the option to undo changes to any file.
Also go through this with David if possible, but it may be easier now to start a new branch and do it again - being careful about files changed. The design you will have to do again, but dialog code you could copy over.

**Comment by aduut** [comment]
Many thanks Danny.

**Comment by dannyparsons** [comment]
Please close this if it is not needed anymore.

**Comment by aduut** [comment]
Ok Danny. Thanks.

*Duut.abib*

*The visual symbols  below are the Adinkra Symbols which were created by
the Akan (a group of people in Ghana). These symbols represent aphorisms or
concepts. For more about these symbols click on the following links:*

*http://en.wikipedia.org/wiki/Adinkra_symbols
<http://en.wikipedia.org/wiki/Adinkra_symbols>*
*http://www.adinkra.org/ <http://www.adinkra.org/>*


*MFRAMADAN <http://www.adinkra.org/htmls/adinkra/mfra.htm>: *"wind-resistant
house":fortitude, preparedness.


NEA ONNIM NO SUA A, OHU <http://www.adinkra.org/htmls/adinkra/neao.htm>:"he
who does not know can know from learning" :knowledge, life-long education

**Pull request closed without merging**
