### PR TITLE
Filter bug

### PR DESCRIPTION
**Pull request by lilyclements**
In progress

Edit @africanmathsinitiative/developers this is ready for review

### CODE REVIEW

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers this is ready for review.

I was going to fix something in this dialog where you would be warned of an overwriting if you tried to name a new data frame as a current sheet name. However, it transpires we plan to do this in the ucrSave itself, rather than in each dialog. As a result, I have made a few minor changes to this dialog which I came across in this process! These are
* TestOK fixed
* Layout
* Tab Order
* Changing SetName to SetPrefix
* Fixed problem where the preview would state: "Current Filter will be removed." at the wrong time

This pull request is not updating the dialog to the most recent version. These are simply fixes for Friday's release.

**Comment by stevekogo** [comment]
@africanmathsinitiative/developers Someone should review this.

**Comment by stevekogo** [comment]
@africanmathsinitiative/developers This is still waiting for a review. Someone should volunteer to have a look at it.

**Comment by stevekogo** [comment]
@Lunalo You pledged to be reviewing @lilyclements pull requests. Here is an emergeny task for you to review.

**Comment by stevekogo** [comment]
@lilyclements Should I go ahead and review this?

**Comment by Lunalo** [comment]
okay Sir , I will review it

**Comment by Lunalo** [comment]
@dannyparsons 

This is ready for you

**Pull request merged**
