### PR TITLE
Three variable modelling implementation

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
@dannyparsons , @volloholic  I have fixed the model subdialogues to be more flexible then implemented the three variable modelling. This is not quite complete but I would like you to check it then get back to me with any suggestions. We might have a Skype call today to discuss this.

**Comment by stevekogo** [comment]
@dannyparsons and @volloholic Can we have discussion today regarding this pull request?

**Comment by stevekogo** [comment]
@dannyparsons I have done some fixing on the dialogue but explanatory variable transformations is not working as it should be. I will keep on improving it.

**Comment by dannyparsons** [comment]
I should prpbably accept this soon since it's changed so many files. Let me know.

**Comment by stevekogo** [comment]
I think you should accept it the way it is then we can keep improving it.

**Pull request merged**
