### PR TITLE
DlgOneWayFrequencies

### PR DESCRIPTION
**Pull request by stevenndungu**
In Progress...
Issue: In R studio, the output of `sjt.frq`  by default is given in the output window  but this can be redirected to HTML  by changing  `use.viewer`  parameter from default as `TRUE`  to `FALSE`.
`sjt.frq(efc$e42dep,use.viewer=FALSE)` -HTML
`sjt.frq(efc$e42dep,use.viewer=TRUE)`- Rstudio output window
@dannyparsons @stevekogo 
Now coming to R-instat I am having a challenge redirecting the output to the R-Instat output window for the case of tables.  The tables (output) are redirected to  HTML which I guess is not what is required. I have tried using iCallType 2 and adding the parameter  `use.viewer` to control this, but apparently this does not help. 

For the graphs - its displaying well on the output window. 
@rdstern , Is the Weights check box supposed to pass `weight.by` parameter ? Just to be sure. otherwise not fully setup but almost

### CODE REVIEW

**Comment by dannyparsons** [comment]
There is a parameter in RunScript for HTML output but this is not accessible from ucrBase yet.  We just need to add that as something which can be set there and passed through to RunScript. If you can do this great, otherwise I can work on it.

**Comment by dannyparsons** [comment]
In future just create the blank dialog first so that can be merged in.

**Comment by stevenndungu** [comment]
Yes, I created it yesterday and I needed to add some changes. So i opted to add more changes since I new you were busy in the conference presentations.

**Comment by stevenndungu** [comment]
Let me try setting it up, in case i miss out on something I will consult you. Thanks

**Pull request merged**
