### PR TITLE
Adding vb code for the population pyramid

### PR DESCRIPTION
**Pull request by maxwellfundi**
@dannyparsons this is not final. i need to tidy it up abit before its done

### CODE REVIEW

**Comment by dannyparsons** [comment]
Is this ready for review yet?

**Comment by maxwellfundi** [comment]
No, there is something little thats remaining to be fixed on it so that it
can be reviewed. I will let you know when its done

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
Ok no problem

**Comment by maxwellfundi** [comment]
@dannyparsons  this has some nicew code too and needs a little tidying to make it working well

**Comment by dannyparsons** [comment]
Good, check with @rdstern again about this.

**Comment by maxwellfundi** [comment]
@dannyparsons do these need to be closed, or merged to be imporved later?

**Comment by dannyparsons** [comment]
Happy to merge if you can resolve the conflicts quickly. Otherwise they can wait till later.

**Pull request closed without merging**
