### PR TITLE
dlgransform–IHelpID

### PR DESCRIPTION
**Pull request by nyagishira**

### CODE REVIEW

**Comment by dannyparsons** [comment]
I wouldn't change too many dialogs in one pull request. If someone edits one of these dialogs, it might cause a conflict and then you might have to redo some of the work. So it's safer to do less dialogs in each pull request.

**Comment by nyagishira** [comment]
ok.

**Comment by dannyparsons** [comment]
Is this ready to accept?

**Comment by nyagishira** [comment]
yes

**Pull request merged**
