### PR TITLE
dlgTwoWayANOVA

### PR DESCRIPTION
**Pull request by nyagishira**
the dialog is not yet working, am stuck

### CODE REVIEW

**Comment by rdstern** [comment]
I wonder which dialogue this is?  There is going to be one-way ANOVA and then General ANOVA.

Roger

**Comment by nyagishira** [comment]
am sorry i did not indicate, Non-Parametric two way ANOVA

**Comment by rdstern** [comment]
This should not be too difficult.

But you should now realise that just saying “I am stuck” makes it difficult to offer advice.  It is like saying “My car doesn’t work for me anymore” without saying whether it is a flat tyre or a problem with the engine, or that you don’t have a car anymore because you have just sold it!

So in what way are you stuck?  Is it to do with VB or R or your computer???

Cheers

Roger

**Comment by nyagishira** [comment]
am stuck in enabling OK

**Comment by rdstern** [comment]
Oh good.  I am sure that is a Danny question!!!

**Comment by dannyparsons** [comment]
This is the same dialog as your other pull request? Can this one be closed?

**Pull request closed without merging**
