### PR TITLE
Adding the new help files

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great, can people be testing the new dialog's help buttons now to check everything is linked up.

**Comment by maxwellfundi** [comment]
Yes. We should now check the new dialogs. @stevenndungu could you have a look at the new dialogs you created for the help ids

**Comment by stevenndungu** [comment]
Checking now.

**Comment by stevenndungu** [comment]
They are all linked up, apart from Climatic>Prepare>Transform... that breaks before showing the dialog. looking the potential bug with @maxwellfundi .

**Pull request merged**
