### PR TITLE
Reference levels

### PR DESCRIPTION
**Pull request by Lunalo**

### CODE REVIEW

**Comment by lilyclements** [comment]
Is this ready for review?

**Comment by stevenndungu** [comment]
@Lunalo what is the state of this ?

**Comment by Lunalo** [comment]
There are few things to fix including the grid

**Comment by stevekogo** [comment]
@Lunalo comment on the state of this.

**Comment by Lunalo** [comment]
This needs new control . So not ready

**Comment by lilyclements** [comment]
By a new control do you mean a current control needs to inherit ucrCore?
Is this the same control as #2608 ?
Should we be writing these things in issues? I think we should.

**Comment by dannyparsons** [comment]
Yes the factor control still needs to be implemented as a core control. Would be good to have an issue for it.

**Comment by maxwellfundi** [comment]
@Lunalo  could you raise the issue on this pull request?

**Pull request closed without merging**
