### PR TITLE
Fixed Four variable modelling

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
Four variable modelling is now up and running. However, there is a slight problem when using glmer and lmer objects  to obtain confidence limits; confint command doesn't seem to apply for these two objects.

A solution could be to uncheck the confidence interval option in the subdialogue as a default and disable it when we apply glmer and lmer. What do you think about this?

**Comment by rdstern** [comment]
That sounds a good solution for now.  Roger

**Comment by lilyclements** [comment]
Once this has been merged can I edit the layout for it @stevekogo ? Want to avoid conflicts so let me know if you plan to work on it after it's been merged!

**Comment by stevekogo** [comment]
@lilyclements You can go ahead and edit the layout once it is merged since I have to handle the general modelling dialogue.

**Comment by dannyparsons** [comment]
Sounds good - @stevekogo Can you add a comment about this in the release notes to explain the temporary fix?

**Pull request merged**
