### PR TITLE
dlgExportgraphasimage

### PR DESCRIPTION
**Pull request by maxwellfundi**
This needs a bit more discussion when @dannyparsons gets here about how we want to save the graphs.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers this is ready for review. 
It is under Describe >Export Graph As Image

**Comment by lilyclements** [comment]
@dannyparsons This is ready for you to review

**Comment by maxwellfundi** [comment]
@lilyclements  i forgot to mention that svglite is needed to run this dialog.

**Comment by dannyparsons** [comment]
Why do we need svglite? I thought ggsave is from ggplot?

**Comment by dannyparsons** [comment]
Ok I see from other comments now.

**Comment by maxwellfundi** [comment]
@dannyparsons the file formats have now been shortened.

**Comment by maxwellfundi** [comment]
@rdstern  we will be needing new help ids for these new dialogs, this one being one of them.

Thanks.

**Pull request merged**
