### PR TITLE
Contrast dialog

### PR DESCRIPTION
**Pull request by Lunalo**
Initial design for contrast dialog addressing #1838

### CODE REVIEW

**Comment by dannyparsons** [comment]
to be merged?

**Comment by Lunalo** [comment]
Not really , you can wait abit

**Comment by Lunalo** [comment]
@dannyparsons , I need you help to fix factor greed to fit the functionality of this dialog

**Comment by dannyparsons** [comment]
What functionality do you need?

**Comment by Lunalo** [comment]
Hi Danny please look at #1843

**Comment by Lunalo** [comment]
@dannyparsons 

Please merge this and i will do the final changes after you have created the grid

**Comment by dannyparsons** [comment]
I checked with Roger and he wants the dialog to set the contrasts for the factor column. We don't want the output to be in a new data frame. So this will need an Instat Object method which we can do together.

**Pull request merged**
