### PR TITLE
Dlg Use date

### PR DESCRIPTION
**Pull request by stevenndungu**
@Lunalo , you can review that as I look at dekades and Pentade

### CODE REVIEW

**Comment by dannyparsons** [comment]
A bit of formatting R code is needed. Ask Maxwell or John for help on that.

**Comment by stevenndungu** [comment]
Ok will do that tomorrow

**Comment by dannyparsons** [comment]
Is this ready now?

**Comment by stevenndungu** [comment]
Yes it is ready. Pentade i will be adding later on.

**Comment by dannyparsons** [comment]
This looks great, and R code is formatted very nicely.

**Comment by rdstern** [comment]
Can we call it dekad - for 10 days please.  That now seems to be accepted.  (Decade is often thought to be 10 years)

For 5 day periods it is pentad - not pentade.

Thanks

**Comment by stevenndungu** [comment]
Thanks, I was working on this bearing in mind pentad and decade are 5 and 10 years periods respectively. Only to read on some article that they are daily periods.

 Thanks Rodger for confirming. Its now even more easier and quick to  implement.

**Pull request merged**
