### PR TITLE
FormMain: Fixing errors on graphics and MAnage menu

### PR DESCRIPTION
**Pull request by Lunalo**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Did you need to delete scatter plot?

**Comment by Lunalo** [comment]
Yeah.... scatter plot is now not part of graphics menu and so another option was to exclude it

**Comment by Lunalo** [comment]
Should I include it from the backup?

**Comment by dannyparsons** [comment]
It's fine we can add it in later if needed.

**Comment by Lunalo** [comment]
Okay thanks

**Pull request merged**
