### PR TITLE
Dlg StemandLeaf

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers This is ready for review

### CODE REVIEW

**Comment by Lunalo** [comment]
Hi @lilyclements 

This dialog is useful but unfortunately,  is not called anywhere in the software.

**Comment by lilyclements** [comment]
Yep but presumably it will be called somewhere eventually? I know others have been editing dialogs not called anywhere (yet?). I've just called in the software temporarily when I've tried to test it out :)

**Comment by Lunalo** [comment]
Okay, I will go ahead to review it

**Comment by Lunalo** [comment]
@dannyparsons 

This ready for merging

**Comment by dannyparsons** [comment]
Seems a shame to have this dialog working well but not in any menu. Can we add it somewhere @rdstern?

**Pull request merged**
