### PR TITLE
Connecting Dlgs to FrmMain

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by stevenndungu** [comment]
Made this changes on 7th morning, only to realize now that they did not make up in the list of commits made. a silly mistake made.

**Comment by lilyclements** [comment]
I have a few requests of things to add while you're on the main form if that's okay!

1. Describe - Specific, can you change dotplot... to "Dot Plot..."
2. Describe - Specific, can you add "..." to the end of "Rug Plot"
3. Describe - Specific, can you make "Windrose..." to "Wind Rose..."

4. Climatic - File, can you add "..." to the end of "Define Climatic Data"

5. Organise - Column: Generate, can you change "Permute Rows..." to "Permute Columns..."

**Comment by stevenndungu** [comment]
Its Okay. Let me add them.

**Comment by stevenndungu** [comment]
4 here has the three dots.

**Comment by lilyclements** [comment]
Great, thanks! My version didn't have the three dots so I must be on an older branch.
After speaking to John, we said that I'll merge this into my own branch and add the things in the list in #2466 that haven't been
Is that your understanding too?
Additionally, have you added in the Help ID's or shall I get started on that?

**Comment by stevenndungu** [comment]
Yes, I did all those things, ie, created the new dialogs then  added the
helpIds. What I did but failed to commit the change is connecting to the
frmMain. The dialogues are not displayed at the respective sub menus where
they are to be called.  This should have been included in version 0.1.1.

**Comment by lilyclements** [comment]
I don't think I fully understand. Can we talk on skype?

**Comment by stevenndungu** [comment]
There is no electricity now. Let's talk when power is back (my laptop is
off). Am using my phone.

**Comment by dannyparsons** [comment]
Is this finished?

**Comment by lilyclements** [comment]
So there's one small thing to do I believe. Steve just messaged me and so I think he's about to do it! It's just linking one up to a dialog (Cli-something)

**Comment by stevenndungu** [comment]
@lilyclements,It was DlgClidata. It could not be displayed because it was disabled. Thanks
@dannyparsons , it is okay now. But some of the added dialogues the help button does not redirect to the help browser yet the help ID given by Roger is included in the code. Perhaps you may advice. Thanks

**Comment by stevenndungu** [comment]
this is now finished

**Pull request merged**
