### PR TITLE
Additions on the windrose dialog

### PR DESCRIPTION
**Pull request by maxwellfundi**
@dannyparsons  this is not final as well. Few additions remaining after discussion maybe

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons this was almost working and only a few things were left fot this to work well. 
@rdstern  i think we can discuss this to finish up the windrose

**Comment by dannyparsons** [comment]
good, discuss with Roger before implementing as it may be more complicated and so lower priority

**Comment by maxwellfundi** [comment]
@dannyparsons do these need to be closed, or merged to be improved later?

**Comment by dannyparsons** [comment]
Happy to merge if you can resolve the conflicts quickly. Otherwise they can wait till later.
Add your review

**Comment by maxwellfundi** [comment]
Closing this as am looking into how to do it better. @dannyparsons  i have saved this code too

**Pull request closed without merging**
