### PR TITLE
Permute columns

### PR DESCRIPTION
**Pull request by lilyclements**
This is not giving any output. This was an issue prior to changing NUDs.
Should I add this to the issues page? I'm not sure how we have the output calculated

### CODE REVIEW

**Comment by dannyparsons** [comment]
It seems that is it passing in `size = 0` so no values are generated. It should be the length of the data frame, can you see why this is from the code?

**Comment by lilyclements** [comment]
Great, so we had this issue on another branch too. I'll look into it. Thanks!

**Comment by lilyclements** [comment]
I think I've sorted it?

**Comment by dannyparsons** [comment]
Great. Also the name of the dialog and name of the menu item are different. But that would need frmMain changes so could be done separately.

**Pull request merged**
