### PR TITLE
Ucrgrid basic Structure

### PR DESCRIPTION
**Pull request by Lunalo**
This is my thoughts on how we should implement .

Both The factor and General grid should inherit from ucrGrid hence being able to override methods of ucrGrid. 

This is in progress

### CODE REVIEW

**Comment by dannyparsons** [comment]
Just wondering if we need both ucrGrid and ucrGeneral? 
Maybe you could explain what you would see as the different uses of these two?

**Comment by Lunalo** [comment]
@dannyparsons 

I was basing on the libraries used but after further thinking I think it should be only one control ?

**Comment by dannyparsons** [comment]
I think so yes. One standard grid control and one specific factor grid makes sense.

**Comment by Lunalo** [comment]
@dannyparsons 

So I think the specific factor grid should inherit from standard grid control ?

**Comment by dannyparsons** [comment]
Yes. Any specific grid control should inherit from a base grid control.

**Pull request closed without merging**
