### PR TITLE
Translations work

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Thanks for doing this. If the new version of the translation toolkit won't require manual tagging then I suggest we don't spend any more time on tags now.

**Comment by maxwellfundi** [comment]
yeah, i understand this but i was just testing something on the
translations and thought i would be nice to keep them so if this is not
merged i can close it

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
That's fine. Happy to merge, and for you to keep doing bits on this just don't want you to spend lots of time on tagging now that it won't be needed soon.

**Comment by maxwellfundi** [comment]
yeah i get it


Regards
Maxwell Fundi
|| Phone :+254728508241||

**Pull request merged**
