### PR TITLE
Two sample non parametric test 

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by dannyparsons** [comment]
It's conflicting with the changes John just made on frmMain I think. Can you undo frmMain changes and then I think it can merge.

**Comment by maxwellfundi** [comment]
This is funny, i didnt see if this had conflicts at all. How do i undo the frmMain alone?

**Comment by maxwellfundi** [comment]
@dannyparsons  This is now fixed

**Comment by dannyparsons** [comment]
Great, remember to add the frmMain parts back in to another pull request at some point.

**Pull request merged**
