### PR TITLE
Changes to RclsFunctioby david

### PR DESCRIPTION
**Pull request by aduut**

### CODE REVIEW

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by aduut** [comment]
Danny this pull request submits changes made my David to the SetAssignTo method on the clsRFunction. He may have mentioned this to you by now. There is yet another commit of a change made by him. Thanks

**Comment by dannyparsons** [comment]
Thanks, you can now delete the branch since it's been merged.

**Pull request merged**
