### PR TITLE
Dlg combine

### PR DESCRIPTION
**Pull request by lilyclements**
Work on combine. Still ongoing

### CODE REVIEW

**Comment by lilyclements** [comment]
Reached Problem: GetVariableNamesAsList() which means I can't go any further right now on this

**Comment by lilyclements** [comment]
@africanmathsinitiative/instat  this can be reviewed. It still needs an important feature to be implemented so it cannot be tested properly, however, Danny said we can merge dlgs waiting for important features and so the code so far can be reviewed

**Comment by maxwellfundi** [comment]
@dannyparsons  this code looks good. You could have a look.

**Comment by lilyclements** [comment]
@dannyparsons I made the necessary changes

**Pull request merged**
