### PR TITLE
Work on combine graphs

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  i have implemented this and i have an issue with passing the list of graphs to the list()
here is the function am currently running- grid.arrange(grobs=list(c(Boxplot1,Bar1)), nrow=36, ncol=7)
but does not work well, i have tested this in R and works without the c()- and it works. 
I am not sure how to get rid of the  c() when getting the variablesnames from the multiple receiver.
We can have a chat on this when you are available.

**Comment by dannyparsons** [comment]
Hi Maxwell, firstly, why are you getting the variable names? How can the function work if you pass in a list of strings, when it needs a list of graphs?
A similar thing to what you want was needed for the Combine Text dialog, where the variables had to be passed in one by one. I think if you look how this was done you could easily adapt it. The difference is, you might want to have an RFunction for the "list" and then add the graphs to that RFunction (although you don't actually have to pass the graphs in as a list for the function to work).
Also, 36 rows and 7 columns layout for 2 graphs seems very strange...

**Comment by maxwellfundi** [comment]
@dannyparsons okay let m have a look

**Comment by maxwellfundi** [comment]
@dannyparsons i am closing this. Formatted my machine and i have had trouble getting one of my branches. I am putting up this work again.

**Pull request closed without merging**
