### PR TITLE
Dlg water balance

### PR DESCRIPTION
**Pull request by lilyclements**
Added column name option

### CODE REVIEW

**Comment by Lunalo** [comment]
The code is in a good shape. Just let me know when you are done editing

**Comment by lilyclements** [comment]
Great thanks, it will need to be merged into todays version ideally, however, there could still be things to add to this so it's not properly ready for review yet

**Comment by lilyclements** [comment]
@Lunalo can you re-review this please?

**Comment by Lunalo** [comment]
This looks good.

@dannyparsons  should have a look

**Pull request merged**
