### PR TITLE
Added ncdf4 package to Rsetup

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
@africanmathsinitiative/instat Once @dannyparsons merges this branch, install ncdf4 package to Rstudio.

**Comment by lilyclements** [comment]
Can you also add in these two packages:
EnvStats
signmedian.test

Thanks!

**Comment by stevekogo** [comment]
@lilyclements I have added the two packages to Rsetup so that they can me merged together

**Comment by dannyparsons** [comment]
This needs to be done in a more complex way now, because we need to also think about dependencies and our offline repo of packages etc. So it's not just this file that changes. If someone can keep a list of new packages then I can add them before the next release.

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers if you have a package that needs to be added could you kindly reply to this with the name of the package so that @dannyparsons  adds them and this is closed.

**Comment by dannyparsons** [comment]
@lilyclements Has a list of packages needed. Maybe post this in an issue and others can also add to it. I can update for the next installer.

**Comment by maxwellfundi** [comment]
Okay. 

Thanks.

**Pull request closed without merging**
