### PR TITLE
Output, Log and Script windows

### PR DESCRIPTION
**Pull request by deaspo**
Hi @rdstern I have added the keyboard shortcuts for CTRL+A and CTRL+C for selecting all text and copying selected text to the three windows.

### CODE REVIEW

**Comment by rdstern** [comment]
Great.  Delighted.

Roger

**Comment by dannyparsons** [comment]
Hi Polycarp, what was the reason for using KeyUp event? KeyDown would have been my default choice.

**Comment by deaspo** [comment]
The difference between the two events is minimal, only copy when the pressed keys have been released (KeyUp). Suppose am pressing CTRL + A, then before releasing press another key say X, that is registered as CTRL + A + X which equals select all and cut. That's why I prefer KeyUp

**Comment by dannyparsons** [comment]
Great, thanks for the explanation and example. It's clear now.
My next question is with KeyUp, does it matter which key I release first?
If I release CTRL before C or the other way round, or together, does that
matter?

**Comment by deaspo** [comment]
I have just tested it, for it to copy or select all, you have to release A or C first then ctrl. If you release ctrl first nothing happens. In addition, the order is you have to press ctrl first then the other keys if it is to work. So you cannot start with A/C then ctrl.

**Comment by dannyparsons** [comment]
To me that seems a good argument not to use KeyUp then doesn't it? The
typical behaviour in other programs is that you have to have Ctrl pressed
when you press A or C, but not when you release. To me that suggests the
copying is done on KeyDown.

And the KeyDown can still do something like Ctrl + A + C because that will
just raised the KeyDown event twice, the first will select all and the
second will copy all that's selected, so I don't see that being a problem.

KeyPress is another option but I don't think it has the e.Control that we
need.

**Comment by deaspo** [comment]
@dannyparsons  Changed KeyUp to KeyDown.

**Pull request merged**
