### PR TITLE
Inventory plot fixes

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
@africanmathsinitiative/instat This is now ready for review

**Comment by lilyclements** [comment]
@stevekogo I am reviewing and making changes to this dialog now. I will then merge it back into this branch

**Comment by stevekogo** [comment]
@lilyclements How did you go about reviewing this and adding code?

**Comment by lilyclements** [comment]
@stevekogo apologies, I closed the branch where I made changes. I have now reopened it and it's ready to be merged

**Comment by lilyclements** [comment]
@dannyparsons this is ready to review

**Pull request merged**
