### PR TITLE
Main form

### PR DESCRIPTION
**Pull request by lilyclements**
Enabled a few things we disabled for Beta

### CODE REVIEW

**Comment by dannyparsons** [comment]
I'm actually happy to keep these disabled until they are working.

**Comment by dannyparsons** [comment]
See my comment above, unless there's a reason these need to be enabled?

**Comment by lilyclements** [comment]
Okay. I was starting to work on the chi square dialog so wanted it enabled so I could check how it's going. However, I can just change chi square on a branch, temporarily enable it on the main form and undo the enable then make my pull request. Shall I close this? I'm not going to be able to work on it for a few days now anyway!

**Comment by maxwellfundi** [comment]
Yeah, i suggest if its temporary for your local use, you could close this. Else it its working well and ready to get into the master then this could be re-enabled.

**Pull request closed without merging**
