### PR TITLE
Tidying up some Corruption Dialogs

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/developers This is ready for review.

These are very _very_ minor changes I made over the weekend. I have only tidied up:
* DefineCRI
* DefineRedFlags
* StandardiseCountryNames

So this should be a very quick review!

### CODE REVIEW

**Comment by stevekogo** [comment]
@africanmathsinitiative/developers Someone should review this. It won't take mucc time since they are minor edits.

**Comment by stevekogo** [comment]
@africanmathsinitiative/developers  This is quite a simple task which someone should quickly have a look at. Such minor changes should be reviewed within the shortest time and merged in.

**Comment by stevekogo** [comment]
@rdstern I have discussed with Merceline and we will work on an example. I will keep you posted on how this goes.

**Comment by lilyclements** [comment]
@stevekogo did the above comment mean to go in this dialog or is it meant to be in the Climsoft one?

**Comment by AlexSananka** [comment]
@stevekogo (pull request manager) I am reviewing this.

**Comment by AlexSananka** [comment]
This is looking fine,except on dlgDefineCRI where we have an empty sub `
    Private Sub cmdEdit_Click(sender As Object, e As EventArgs) Handles cmdEdit.Click

    End Sub`I undestand this button is currently disabled but do we need this sub?If we do then I think there should be a statement showing that it's needed maybe in future?

**Comment by AlexSananka** [comment]
Otherwise the designer of the dialogues are looking nice and attractive,after the above has been addressed then @dannyparsons  can merge this.

**Comment by lilyclements** [comment]
@AlexSananka I kept the sub, but I've added in a comment explaining why it's empty. Can you let Danny know whether this is ready for reviewing?

**Comment by AlexSananka** [comment]
@dannyparsons  This ready for you to review

**Pull request merged**
