### PR TITLE
Manage menu

### PR DESCRIPTION
**Pull request by Lunalo**
Changes on the delete Rows or columns dialog

### CODE REVIEW

**Comment by Lunalo** [comment]
I have deleted the delete column dialog. You can merge and then I can work on the latest version

**Comment by dannyparsons** [comment]
There are some changes to make here. I'll accept so you can get the latest version first.

**Comment by deaspo** [comment]
Hi @dannyparsons  and @Lunalo , 
error

**Comment by Lunalo** [comment]
Hi Polycarp,

I have already sent the resource files

Regards,
John Ong'ala Lunalo|| Kenyatta University Alumnus||
Volunteer, African Maths Initiative||
Email Address :johnlunalo95@gmail.com
Tel: +254701519572, +254786438572

**Pull request merged**
