### PR TITLE
dlgReorderLevels-adding method and organising the designer

### PR DESCRIPTION
**Pull request by nyagishira**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great, before I look at it too much, have the other team members tried the dialog and tried to break it? And have you got their comments on the design?

**Comment by nyagishira** [comment]
am only organising the designer for now....on the design they agree

**Comment by nyagishira** [comment]
am sorry, let me give them to try break it.....

**Comment by nyagishira** [comment]
Max has tried to break it by plots but its working nicely

**Comment by dannyparsons** [comment]
Great I will ask Beth to have a look at it now.

**Comment by bethanclarke** [comment]
The code works well, good job.

I liked the layout of the dialogue before you added the code - when the data frame selector and the single factor receiver were aligned with each other and Available Variables and Available Factors were aligned with each other. 

What was the reason for changing the design? There is much more blank space now.

**Comment by nyagishira** [comment]
the dialog is back to the way it was...i had changed the layout because i thought the receiver was better off alighned with the add button of the ucrasaelector.

**Comment by bethanclarke** [comment]
Thanks Mary. On some dialogues it would be good to have the receiver aligned like that, But because we have the grid displaying the factor levels underneath the single receiver, it creates a lot of unused space.

**Pull request merged**
