### PR TITLE
Adding Geoms... and aes receivers ! (ucrGeom ucrGeomListWithAes)

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**

### CODE REVIEW

**Comment by FrancoisJRenaud** [comment]
# dlgGeneralForGraphics code generated by the dialog General 
survey_temp <- InstatDataObject$get_data_frame(data_name="survey")
survey_by_Village._temp <- InstatDataObject$get_data_frame(data_name="survey_by_Village.")
ggplot(mapping=aes(colour=Village., y=Yield, x=Fert), data=survey_temp) + geom_point() + geom_hline(inherit.aes=FALSE, mapping=aes(yintercept=Yield, colour=Village.), linetype=4) + xlab(label="") + ylab(label="") + facet_grid(facets=. ~ Village.) + geom_hline(inherit.aes=FALSE, colour="black", mapping=aes(yintercept=GlobalYieldMean)) + geom_hline(inherit.aes=FALSE, mapping=aes(yintercept=mean.Yield, colour=Village.), data=survey_by_Village._temp)
hline_example

**Comment by FrancoisJRenaud** [comment]
So I ve done my testing. It should be fine now, apart from certain problems with incompatible parameters and other concerns raised and commented in ucrGeom. Should not be crashing the software though ...

**Comment by FrancoisJRenaud** [comment]
So I ve done my testing. Added geoms abline, vline, hline, label and text. It should be fine now, apart from certain problems with incompatible parameters and other concerns raised and commented in ucrGeom. Should not be crashing the software though ...

**Comment by FrancoisJRenaud** [comment]
@africanmathsinitiative/instat  Hi everyone. Could someone review this ?

**Comment by FrancoisJRenaud** [comment]
@maxwellfundi Hey Omeera !  could you have a look at this ? Just copy the ucrGeom as it is here and do some testing ?

**Comment by maxwellfundi** [comment]
Francisco, am sorry I am in a rural place as you saw with quite limited
options for Internet connection.  Sorry I didn't see this in time.

**Comment by FrancoisJRenaud** [comment]
haha, no worries ;)

**Pull request merged**
