### PR TITLE
Create model operators user control

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by volloholic** [comment]
Hi Steve 
I'm sorry I didn't realise you haven't been discussing with Beth. I think the current thinking is that a combo box might do this job better. I don't know whether that means we should put a combo box into this user control or whether there is no need to create a user control.
David

**Comment by stevekogo** [comment]
@volloholic I will close the pull request and implement the operators in a combobox

**Comment by dannyparsons** [comment]
Hi Steve, I've been discussing with @bethanclarke and she is implementing a combo box for the model operator on the three variable modelling dialog. She said she thinks you are working on the four variable dialog. 
So I just want to check that you two are not overlapping on tasks. If you are working only on four variables at the moment then it should be fine, but let me know.

**Comment by stevekogo** [comment]
@dannyparsons I am going to close this pull request now. I have already implemented the model operators combo box in four variable which I have submitted under pull request 1528. I was working on three variable modelling today but I have not submitted the pull request. It is fine if Beth implements this.

**Pull request closed without merging**
