### PR TITLE
Re-implementation of climdex dialog

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@stevekogo This is really great. I tried it with dodoma data, 80 years, and did all the indices and it all worked! The output was and R codes are long, but that's ok.

I think we can simplify the codes easily by assigning the output of the climdexInput.raw function to something like "climdex object". Then we won't get the long definition of the object for each index.

Eventually we will want the output to be able to go back in a dataframe, as well as the output window. But I think that can come later.

The assignment change you could make now and should make the code look nicer.

**Comment by stevekogo** [comment]
@dannyparsons Thanks for carrying out the testing. I will assign the output to an object then resubmit.

**Comment by rdstern** [comment]
This sounds just great.  Well done Steve.

**Comment by stevekogo** [comment]
@dannyparsons Have a look at it.

**Pull request merged**
