### PR TITLE
dlg Remove Unused levels

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by stevenndungu** [comment]
@africanmathsinitiative/instat this is too ready for review

**Comment by Lunalo** [comment]
This is generally working fine

**Comment by Lunalo** [comment]
@dannyparsons  @volloholic  

Do we need to handle controlContentsChanged for the ucrSelector if we are only doing a check for the receiver in the TestOKEnabled?

**Comment by dannyparsons** [comment]
If the control is not part of test ok then we don't need to handle it's event for test ok. So here we probably don't need the selector.

We just need to make sure still that OK is **not** enabled when you have no data loaded. This is usually ok because we have receivers on most dialogs.

**Comment by stevekogo** [comment]
@stevenndungu make sure you put your name on the dialogs you are working on in the excel sheet

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers this is ready for review.

**Comment by lilyclements** [comment]
This looks good, @dannyparsons this is ready for you to review

**Pull request merged**
