### PR TITLE
Dialogue for Rownames/Numbers. Not fully functional yet.

### PR DESCRIPTION
**Pull request by aduut**
Danny I would like you to have a look at this for me, I haven't gotten it to work well yet. Use your usual questioning and pointers that should be helpful, thanks.

### CODE REVIEW

**Comment by dannyparsons** [comment]
Hi Abib, if you let me know what is working and what you know is not working yet then I can help you much better. 
It would be better if you ask me specific questions where you are stuck instead of just saying it's not fully functional.

**Comment by aduut** [comment]
That was just for the title.

I sort of gathered from David that you look thoroughly at the code.

Apologies.

*Duut.abib*

*The visual symbols  below are the Adinkra Symbols which were created by
the Akan (a group of people in Ghana). These symbols represent aphorisms or
concepts. For more about these symbols click on the following links:*

*http://en.wikipedia.org/wiki/Adinkra_symbols
<http://en.wikipedia.org/wiki/Adinkra_symbols>*
*http://www.adinkra.org/ <http://www.adinkra.org/>*


*MFRAMADAN <http://www.adinkra.org/htmls/adinkra/mfra.htm>: *"wind-resistant
house":fortitude, preparedness.


NEA ONNIM NO SUA A, OHU <http://www.adinkra.org/htmls/adinkra/neao.htm>:"he
who does not know can know from learning" :knowledge, life-long education

**Comment by dannyparsons** [comment]
Yes, if you submit something that you have worked on and think is complete, I will look at it and see if there is anything to be corrected or improved.

You can also submit incomplete code, as you've done here, because this is a good way to have discussion and get help. But only if you specify where you need help or what needs to be discussed. For example, you've said you haven't got it to work well yet. Is this because you are stuck and need help on the next step? Or is this just where you have got to and you are continuing from here? Either is fine, but without at least knowing this I don't know how to respond to help you. The more information you give me the better I will be able to respond.

**Comment by aduut** [comment]
Hello Danny,

Got it, thanks.

Hope you are having a nice day.



*Duut.abib*

*The visual symbols  below are the Adinkra Symbols which were created by
the Akan (a group of people in Ghana). These symbols represent aphorisms or
concepts. For more about these symbols click on the following links:*

*http://en.wikipedia.org/wiki/Adinkra_symbols
<http://en.wikipedia.org/wiki/Adinkra_symbols>*
*http://www.adinkra.org/ <http://www.adinkra.org/>*


*MFRAMADAN <http://www.adinkra.org/htmls/adinkra/mfra.htm>: *"wind-resistant
house":fortitude, preparedness.


NEA ONNIM NO SUA A, OHU <http://www.adinkra.org/htmls/adinkra/neao.htm>:"he
who does not know can know from learning" :knowledge, life-long education

**Comment by aduut** [comment]
Hello Danny,

​What would be next dialog you would have me work on?

I have worked a bit on the Freeze dialog, but I haven't been able to
actually freeze any columns yet, I wonder if there is "set_freeze_columns"​
in the climate Object.

I am currently cloning the climate object so that I could have a somewhere
to implement and see how it works, so I would be able to implement this
carefully.So once that is done, I think I would be able to finish up the
Freeze and Rownames dialog, which would inevitably reduce me and you time,
and broaden my understanding of things.

Or what do you think?

Thanks.

*Duut.abib*

*The visual symbols  below are the Adinkra Symbols which were created by
the Akan (a group of people in Ghana). These symbols represent aphorisms or
concepts. For more about these symbols click on the following links:*

*http://en.wikipedia.org/wiki/Adinkra_symbols
<http://en.wikipedia.org/wiki/Adinkra_symbols>*
*http://www.adinkra.org/ <http://www.adinkra.org/>*


*MFRAMADAN <http://www.adinkra.org/htmls/adinkra/mfra.htm>: *"wind-resistant
house":fortitude, preparedness.


NEA ONNIM NO SUA A, OHU <http://www.adinkra.org/htmls/adinkra/neao.htm>:"he
who does not know can know from learning" :knowledge, life-long education

**Comment by dannyparsons** [comment]
Hi Abib,
A couple of questions:
Why are you asking for new dialogs when you still have dialogs not finished yet?
I hope you mean the Instat Object and not the Climate Object? We are not doing anything with the climate object at the moment. Either way you shouldn't be copying or cloning anything again. That's what branches are for. If you want to test something use a new branch. You can always delete a branch or undo the changes on it so this is safe.
You are right there is no freeze columns method yet. We can discuss this and decide if it's sensible for you to write the R method or someone else and you do the dialog. Because that's not written yet, I suggest focusing on the row names dialog first and get this complete before moving to anything else.

**Comment by aduut** [comment]
Hello Danny,

Answers to a couple of questions.

The climate object. Not the Instat object since I gather most of the
functionality transfer from there. Now since I am more familiar with that,
understanding and replicating functionality in the Instat -R would be much
easier.

When can we discuss the R code for the freeze columns?

I would revisit the Rownames, tomorrow. As I wait for a good time for the
Freeze column discussion.

I would do a pull request for the Freeze anyway. How does that sound?





*Duut.abib*

*The visual symbols  below are the Adinkra Symbols which were created by
the Akan (a group of people in Ghana). These symbols represent aphorisms or
concepts. For more about these symbols click on the following links:*

*http://en.wikipedia.org/wiki/Adinkra_symbols
<http://en.wikipedia.org/wiki/Adinkra_symbols>*
*http://www.adinkra.org/ <http://www.adinkra.org/>*


*MFRAMADAN <http://www.adinkra.org/htmls/adinkra/mfra.htm>: *"wind-resistant
house":fortitude, preparedness.


NEA ONNIM NO SUA A, OHU <http://www.adinkra.org/htmls/adinkra/neao.htm>:"he
who does not know can know from learning" :knowledge, life-long education

**Comment by dannyparsons** [comment]
I'm not sure what you mean about the Climate Object. But I don't think looking at it now is good use of your time at all. We may change the climate object substantially soon so you might be wasting your time by understanding it in it's current form. Once we begin work on climate dialogs in R-Instat and make changes to the climate object then it would be good for you to understand it, but not now.

If the design for freeze columns is done then happy for you to do a pull request for that, and then you can do another branch later for adding the code. This is how John often does dialogs.

As I said before because the R code for freeze columns has not been written yet, I suggest focusing on the row names dialog first and get this complete before moving to anything else. After you have done row names, we can discuss the code for freeze columns.

**Comment by aduut** [comment]
Thanks Danny.

I would do the pull later today.

Thanks again.

**Comment by aduut** [comment]
Hello Danny, so I have polished up the code for the Rownames, I got all the basic functionality on the specification working but for the copy to column which David added. I can only get the ucrNewColumnName... to display after I have selected another option different from copy to column, which is the condition that should display. To state it more clearly, if load the dialog and the first thing I do is to check the copy to column option it the ucrNewColumn... does not display, until I have checked another option then come back to select copy to column before the ucrNew... displays. I played around with initialize dialog options, but it didn't work. Any ideas?

Now to the core functionality. Now most of the options in the groupbox are to be disabled on default. The ones that are enable are not functioning well, I am not able to extract the rownames from the object and copy it to a column, or sort based on the rownames. Would you have some time to help me?

**Comment by dannyparsons** [comment]
There is some tidying to be done but we can go back to that after you add the third option. The first two options look good now.

**Pull request merged**
