### PR TITLE
Editing the FrmMain (Corruption, Keys and Links,... menus)

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by dannyparsons** [comment]
I think the names of these dialogs need to be more specific e.g. dlgCorruptionDescribe.vb instead of dlgDescribe.vb.

**Comment by stevenndungu** [comment]
OK ,let me edit that

On Jan 5, 2017 19:37, "Danny Parsons" <notifications@github.com> wrote:

I think the names of these dialogs need to be more specific e.g.
dlgCorruptionDescribe.vb instead of dlgDescribe.vb.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/africanmathsinitiative/Instat/pull/2462#issuecomment-270690631>,
or mute the thread

**Comment by dannyparsons** [comment]
Great that the dialog names are changed, but the actual file names i.e. the .vb parts are still the same like dlgDescribe.vb

**Comment by stevenndungu** [comment]
Sorry, Where should I edit the name from,  i have edited from the
properties of the dialogue but it has not changed it ...

**Comment by dannyparsons** [comment]
I think also edit the actual file name in the list of dialogs in the Solution Explorer.

**Comment by stevenndungu** [comment]
Thanks, it has changed

**Comment by dannyparsons** [comment]
Something's not quite right still because the designer files like dlgDescribe.Designer.vb still have the old name. Does it show like that on yours?

**Comment by stevenndungu** [comment]
Let me check.

**Comment by stevenndungu** [comment]
This is how it appears on my computer.. the names have changed...but could not be seen on the pull request I made- changes were not reflected....
image

**Comment by stevenndungu** [comment]
Thats taking the example of DlgCorruptionFile

**Comment by stevenndungu** [comment]
I think if I make changes on any of the file, the changes could be seen. I guess..._

**Comment by stevenndungu** [comment]
From the above check. on  subsequent pull requests the specific corruption names are configured as expected.

**Comment by dannyparsons** [comment]
Try making a change on the designer instead.

**Comment by stevenndungu** [comment]
OK..

**Comment by stevenndungu** [comment]
will undo the changes

**Comment by stevenndungu** [comment]
Does it look Ok?

**Comment by dannyparsons** [comment]
Yes! That works for the designers. But the resx files - some are missing and some have the old name still. Can you make sure they are not excluded and maybe make any change on them so they update?

**Comment by stevenndungu** [comment]
OK fine.

**Pull request merged**
