### PR TITLE
Graph output test (warning: frmMain, dlgGeneralForGraphics and many others !!)

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**
This is a first draft for outputting graphs in output window. Also added a webBrowser that's not really functional yet...

### CODE REVIEW

**Comment by dannyparsons** [comment]
I tried to run this but got an error starting the software in frmWebBrowser line 13
> An unhandled exception of type 'System.ArgumentException' occurred in System.Windows.Forms.dll
> 
> Additional information: ObjectForScripting's class must be visible to COM.  Verify that the object is public, or consider adding the ComVisible attribute to your class.

**Comment by dannyparsons** [comment]
If I comment out that line it works though. The graph in both! Just very large!

**Comment by FrancoisJRenaud** [comment]
Yeah, the webBrowser control is not really mastered yet... There are a few things I didn't get yet, but @volloholic told me to not implement something that was working all smoothly.  Did you try to produce several graphs see if it displays the subsequent ones ?

**Comment by maxwellfundi** [comment]
The size of the graphs was also an issue to me. They looked enormous bit my suggestion was to save the graphs with a standard (pre defines size). ggsave has an option of including height and width of the image and this would then help with resizing thee graphs. 
I was also wondering if we could have a way to make the size relative to where we want to display it.

**Comment by FrancoisJRenaud** [comment]
Just trying to have the graph displayed at a reasonable size. For the moment it adapts to the size of the output window just before pasting. There is a possibility to resize the graph, but only if the ReadOnly mode of the output window is set to False. Didn't manage to implement something that would resize the graphs as the output window is resized as I don't know how to access the graph within the RTB. Might be easier to do so if we manage to add the graph by using the rtf code...

**Comment by dannyparsons** [comment]
Great that are options to resize, either at exporting or importing. The exact way we decide on sizes can be discussed, I'm not sure proportional to the window is exactly what we need. 
I don't think being able to resize in the output window is important, I see the output as a static record, not something to change.
Is it easy to detect if an image has been click on (or double clicked)? That could be a way of getting the graph to pop up in it's own window and then you can see it in different sizes.
Another small point, is it easy to include a thin black border on the images? Would look nice in the output window I think.

**Comment by FrancoisJRenaud** [comment]
Mhm I was hoping that a double click on the graph would be detectable, but without any grasp on how it is stored in the RichTextBox it seems difficult to me. Could you send me the documentation you were reading when you told me that there is no FlowDocument in the windows.forms type of project ? I would like to understand this better. 
Otherwise I ve been working on how to avoid using the clipboard as recommended by @volloholic .

**Comment by FrancoisJRenaud** [comment]
One possibility is to set WrapText to False, and have two scrollBars... Would be more convenient on the graphics side, and the text wouldn't be displayed in very very long lines anyway, as we keep having newline (being in multiline mode).

**Comment by dannyparsons** [comment]
Here http://www.wpf-tutorial.com/rich-text-controls/introduction/ it basically says it's only for WPF.
Also found this: http://stackoverflow.com/questions/33405168/winform-richtextdocument-flow-document which claims you can have a WPF form inside a WinForm project, might be worth looking into.
You can google WinForms vs WPF to get a general overview of both.

**Comment by FrancoisJRenaud** [comment]
Aha ! that sounds quite good ! I will try :) the WPF RichTextBox is so much more flexible then the WinForm one, so that would really help...

**Comment by FrancoisJRenaud** [comment]
So @africanmathsinitiative/instat  I m quite excited to announce that the new "WPF Output Window" looks really good so far ! Implementation of things to output is much easier and more flexible than with the previous version using a windows forms richtextbox. Graphics appear in much better quality, I have been able to add a border as @dannyparsons  was asking for,... I hope to be able to handle a double click on the graphic tomorrow, so that we can think of opening it in another window, saving, resizing, etc. ... 
It was quite a pain to get the WPF rich text box available in the windows form project, but it was worth it I think ! I would advocate for replacing the old output window with this one... Just need to reduce spacing between different lines, and we will have got what I would call a pretty exciting upgrade of what we had before ! 

Now a small bug that needs to be fixed. One or several methods used to output the graphs in the output windows keeps the folder used to save the grphs busy... So at a second call of ggsave, for the same location, there is an error. It also occurs in R when using ggsave on that same location and the software is still running. Once R-Instat has been closed, ggsave works fine again.

**Comment by FrancoisJRenaud** [comment]
Also the output window is in good progress and I have a clearer picture of what's possible or not. At this stage, it would be good to start making choices so that I don't do 4 times the amount of work that is required. The best implemented option is the WPF RichTextBox that is now including text, graphics and html reader boxes. There are just a few things that need to be fixed, such as the copy of graphs or html reader content, but I am confident that this will be feasable. In general this option is arguably more flexible than the others, but it sometimes requires a bit of coding. A last concern about it is that I add a webbrowser for each html code that is send to the output window (can be in the form of a file, or a string of html code). This might be source of inefficiency ? I am not particularly skilled at efficiency testing. Things seem to run smoothly for now. I ve implemented a class for these "added at run" webBrowsers so that this potential efficiency problem could be handled there.

I had a long and very helpful/pleasant skype with Danny yesterday during which he mentioned I should not put too much efforts on getting the two other output windows to work in case this one is doing all the job well.

However, I would like to suggest another option that you might not have considered yet, which is the use of the knitr R package, which is pretty much doing, again "for free", all, or almost all, what we are trying to display on our output window, and produces it in the form of a html file that can then be read very easily in the webBrowser output window... According to John, this file can be edited dynamically. It is also possible to add our comments and potentially to identify blocks within the html file code, but that might be a bit more tricky... Just an idea... it would require quite a bit of rewriting but it is worth at least knowing the option exists.

There are two remaining options so far. One is using the old output window, which I wouldn't recommend. It has still nice features such as zooming and the copy pasting is doing very well with pictures. However, I think blocks and almost certainly html readers are not available there (would need to translate html to rtf, I ve been exploring translation for the WPF RTB, but it is not a reasonable option, especially when it comes to translate sophisticated tags such as tables, etc...). The quality of the graphics is not as good as in the WPF RichTextBox, and the method to include graphics is copy-pasting from the clipboard...

The webBrowser output window is still quite appealing. The Windows Form version of the webbrowser actually works with some sort of block system like in the WPF RTB. It is based on the structure of the html code itself I think. I haven't been able to get it to work yet, but I hope it would be possible. That might then be a good option as well. Maybe the import of html file could be done by opening different pages ? But I don't really know how it works. Importing strings of Html code could hopefullly be performed within the same document. For the moment this is not working at all as I need to figure out how to deal with the documents supporting the content...

**Comment by dannyparsons** [comment]
@FrancoisJRenaud Can this be closed?

**Comment by FrancoisJRenaud** [comment]
ndio !

**Pull request closed without merging**
