### PR TITLE
Export r objects and R WorkSpace

### PR DESCRIPTION
**Pull request by AlexSananka**
@dannyparsons  this is ready to be merged

### CODE REVIEW

**Comment by AlexSananka** [comment]
@dannyparsons am done editing this,you can now merge?Or should @africanmathsinitiative/developers  have a quick look?

**Comment by lilyclements** [comment]
I THink we already have an extremes dialog which is currently empty? Perhaps it isn't empty. You should check before this is merged so we can avoid having multiple dialogs?

**Comment by AlexSananka** [comment]
@stevekogo and @shadrackkibet should confirm this,I think this a new dialog according to #2976

**Comment by rdstern** [comment]
Just to clarify there are actually 2 different extremes dialogues - or there will be.  This is not the same dialogue in 2 places.  They have different functions.

In **Climatic > Prepare > Extremes** we prepare the data by taking the (usually) daily records and finding the (usually) annual extremes.

In **Climatic > Modelling > Extremes**  we fit extreme value models to the extremes we prepared earlier.  This uses the extRemes package in R.

We have an AIMS MSc student from AIMS Tanzania doing his essay in this area.

**Comment by lilyclements** [comment]
Thank you for clarifying. I think eventually we should rename them as we have dlgExtremes and dlgClimaticExtremes which have names which aren't too informative about what the difference is. However, I don't think we need to do this now.
@dannyparsons this is ready to merge.

**Comment by lilyclements** [comment]
@africanmathsinitiative/developers Am I the only one having a very weird situation where I have updated my branch but cannot find these dialogs?

I'm on the updated branch which has read in other changes. It's also in the Source > Repos > Instat > instat folder as we would expect.

I took a copy of Alex's branch and I couldn't find the dlgExportRWorkspace in the solution explorer. When I looked for where it's being run it's underlined in red and saying there's an error. However, I am still able to run this branch despite all this.

image

image

it's even letting me run the dialog.

Does anyone know whats happened? What is going on?!

**Comment by dannyparsons** [comment]
Not too sure. I will try it too. Maybe delete the branch and start again?

**Comment by AlexSananka** [comment]
@lilyclements Which branch are you using,I have two separate branches am working on this two dialogs on,for Export R workspace I have a branch by the same name as the dialog and that is it for Export R object.

So you could consider pulling my two branches and test the dialog separately.

**Comment by lilyclements** [comment]
My branch I'm using is called "AlexExportRWorkspace"
I checked many times it pulled the right one and it has. It must have because it's running the dialog well and showing all you changes.

I'll delete it and pull it again. This is strange!

**Comment by lilyclements** [comment]
Fixed it. So, I opened "dlgExportRWorkspace" on my master branch, and then changed back to AlexExportRWorkspace and I can now see the changes. I have no idea why this issue happened in the first place, but I've got it now at least!

**Comment by AlexSananka** [comment]
Great

**Pull request merged**
