### PR TITLE
Dlg FreezeColumns

### PR DESCRIPTION
**Pull request by stevenndungu**

### CODE REVIEW

**Comment by lilyclements** [comment]
Is this ready for review?

**Comment by stevenndungu** [comment]
Yes

**Comment by lilyclements** [comment]
Great, this looks good. Only thing to do is to move the selector to (10,10) and the receiver to (..., 60) so that it is aligned nicely. Then it'll be ready for Danny to review

**Comment by dannyparsons** [comment]
@stevenndungu Has the suggested change been made?

**Comment by stevenndungu** [comment]
The alignment of controls is done as suggested. Thanks

**Comment by stevenndungu** [comment]
Just did it it in the above commit

**Comment by lilyclements** [comment]
The receiver is still too high - I think we need to all have a discussion about where we place receivers as I think everyone does it in different places.

**Comment by stevenndungu** [comment]
Made the control alignment suggested and spacing out of controls. This is ready for review once more and hopefully final review

**Comment by lilyclements** [comment]
Great, I believe this is now ready for @dannyparsons to review!

**Pull request merged**
