### PR TITLE
Make date

### PR DESCRIPTION
**Pull request by Lunalo**
Editing the method to change the month formats

### CODE REVIEW

**Comment by Lunalo** [comment]
@lilyclements 

This is ready for testing

**Comment by lilyclements** [comment]
I've was working on dlgMakeDate here and waiting for a merge:
https://github.com/africanmathsinitiative/Instat/pull/2333

There doesn't seem to be any conflicts but perhaps I should add your changes into my branch (or you can add mine into yours) to keep it all in one place?

**Comment by lilyclements** [comment]
If I add your changes to mine, we get an issue with the data_object_R6 so that needs to be added in separately. I am adding in your other changes made to my pull request

**Comment by Lunalo** [comment]
@lilyclements , Just add but not for Data object. I will push them on a separate branch

**Pull request closed without merging**
