### PR TITLE
Functional output

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**
in progress, 
Made little progress with the copy paste problem, but hope to fix this today. Otherwise I  think the implementation for the output window is more centralised than what I had done previously based on the old Output Window. Would need to edit RSyntax to update the methods to the changes made to RParameters and co once these are merged. Also the opportunity to work on how to make it possible to include extra commands run in clickOk and beforeClickOk in the RSyntax. Once this is done, would also need an "output graph" mode for the RSyntax/RLink to call the necessary subs for outputting the graphs (using the iCallType of RSyntax and edit the RunScript of RLink ?). For the moment ggsave and output of graphs sub are only called in the ClickOk event on general for graphics. Also the ggsave saves graphs in the directory for now. @dannyparsons  told me it should go to temp files...

### CODE REVIEW

**Comment by FrancoisJRenaud** [comment]
So copy pasting works fine now, have introduced a copy rich text and a copy image. Also saveOutputWindow, clearOutputWindow work fine. Last thing that's not really nice is the fact that the comment and the rcommand are actually pasted or saved without line break or even space... might want to add a line break, also will need to adjust the block reader to any changes...

**Comment by FrancoisJRenaud** [comment]
I believe this could be reviewed as it is now, maybe just needs some commenting. Probably easier to review together on skype as there is a lot. Warning: need to delete testing facilities before merge, but let them in as long as testing is going on. Testing will be difficult unless the branch is merged on some temp master branch for people to have easy access ? Next step is to edit RSyntax, once that is done, I will be able to explore how to have graphics output automatically, where and how ggsave saves the graphs etc.

**Comment by FrancoisJRenaud** [comment]
So here is my proposal for graphics:
I want to create a file R_Instat_Temp_Graphs in the Temp Files (given by IO.Path.GetTempFile()), maybe in setup ? Or somewhere. 
Then each time a graph is produced (on a dialogue or within an R method) ggsave is called to save that graph in the temp file (either as part of the secondary RCommands that will soon be in the RSyntax, or as part of the R method). 
Then at the end of RunScript, a sub is called to check the content of R_Instat_Temp_Graphs. If there are files in there, use DisplayGraphInOutputWindow sub on these files, then run "unlink" RCommand to delete these graphs once they have been displayed (there are probably alternatives, I am not quite sure we want to use an RCommand here or if I should find a VB command to do it... the RCommand works fine and then the user can see we save the graph, display it, end then dispose it... which is sort of reassuring... maybe teaching good coding practices ??)

Still need to figure out if the "reading in the R_Instat_Temp_Graphs file to find other files" is actually feasable, but I sincerely hope there is a possibility to do this. Maybe you have an idea of how to do this ?

**Comment by FrancoisJRenaud** [comment]
new implementation of graphics saving and display. 
Create temp directory R_Instat_Temp_Graphs in temp files when setting up output window, 
ggsave in the temp directory each time a graph is created (note: use secondary RCommands on dialogues and add lines in RMethods, find appropriate way to name these files: e.g. for dialogues use ucrSaveGraph.strGraphName ), 
check the directory for graphs to output at the end of runscript, 
then if graphs to display, display and then remove from temp directory automatically with vb command.

**Comment by FrancoisJRenaud** [comment]
still need to make choice between different formats to save graphs, but this can be changed at will.

**Comment by dannyparsons** [comment]
This is starting to look really nice. A few points:

- The issue of the re scaling on machines like mine. For now we go for the temporary fix of disabling re scaling, but eventually we would like to modify our controls so that they behave nicely under re scaling. The main issue could be the grid, which doesn't seem to work well with this yet. More information about this is here https://msdn.microsoft.com/en-us/library/mt622670.aspx and http://stackoverflow.com/questions/32242963/win-form-change-its-size-when-i-create-a-wpf-window. The temporary fix is to add this line `<Assembly: System.Windows.Media.DisableDpiAwareness>` to AssemblyInfo.vb file. There doesn't seem to be able side effects from having this from my brief testing.

- I like the border around the images, but I think it would look better if the width of the border was the width of the image, not the width of the output window. Not that important if it's not easy.

- The image quality seems quite poor. In particular, there is a lot of grey fuzziness around any text like the legend and axis labels. I assume this is to do with the exporting from R or in resizing at some point? Could this be improved by changing the file type exported to or how resizing is done?

- The copying of text and images seems to work well. I think we only need one right click item: "Copy" which just copies what's selected.

- It would be nice if I could copy an image by right clicking on it without it being highlighted. Again, not urgent if it isn't easy.

We would also like in our global options the choice of displaying graphs in the output window, in the default R viewer or in separate windows (our own forms). You might not have time to implement this, but it would be good to make sure that the structures that you have in place mean this could easily be done with little changes to the code.

**Comment by FrancoisJRenaud** [comment]
> It would be nice if I could copy an image by right clicking on it without it being highlighted. Again, not urgent if it isn't easy.

What would you then do with the selected text/image, in case you rigth click on an image that's not selected ? Would you abondon that selection and select the image for example, then do copy like usual.

> The copying of text and images seems to work well. I think we only need one right click item: "Copy" which just copies what's selected.

The reason for which I introduced two options is because the basic copy is in rtf and so doesn't paste images (or text formatting) outside of word (actually even wordpad doesn't support rtf images apparently). The copy image enables to copy images and paste in docs that are not reading rtf... I know it is not quite ideal, but it's the compromise I found between good functionality and easy to implement... There is still the issue with the "no linebreak" in the rtf readers but we decided to leave it like that for now with @volloholic ... Any reactions ?

>The image quality seems quite poor. In particular, there is a lot of grey fuzziness around any text like the legend and axis labels. I assume this is to do with the exporting from R or in resizing at some point? Could this be improved by changing the file type exported to or how resizing is done?

Can you test this again ? I think I fixed this earlier...

>We would also like in our global options the choice of displaying graphs in the output window, in the default R viewer or in separate windows (our own forms). You might not have time to implement this, but it would be good to make sure that the structures that you have in place mean this could easily be done with little changes to the code.

cool will have a look at this once I ve got some sleep

**Comment by FrancoisJRenaud** [comment]
about resizing, I added the temp fix and about borders I found a possible fix but didn't implement as my brain is not working and I m not sure it would work very easily... might have to adapt a few of the methods that access the images such as copy image

**Pull request merged**
