### PR TITLE
John - Tidying up Replicate Branch

### PR DESCRIPTION
**Pull request by lilyclements**
@Lunalo This is ready for you to merge back into your branch.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
I was just wondering if it would be much more efficient not to open a new pull request when you update someones branch, but rather doing a pull request to his repo so that he can merge the new changes on theirs, to avoid having two pull requests with similar content.

**Comment by Lunalo** [comment]
@maxwellfundi 

I have just merged @lilyclements  changes. so she can close this

**Comment by dannyparsons** [comment]
@maxwellfundi Yes I like that suggestion. 

The exception is when the editor may want their branched merged directly. For example, if John had completed the code and Lily then just tidied up the design, Lily could do a pull request to be merged which would automatically close John's. In cases where it is being sent back to John for further work, a pull request on the main branch is not needed.

**Comment by maxwellfundi** [comment]
Sounds good @Lunalo  but its more efficient if this pull request was done to your branch

**Comment by lilyclements** [comment]
Good point! Thanks for this, I'll make sure I do that in the future if the plan is to merge it back to a branch.

**Pull request closed without merging**
