### PR TITLE
dlgPolynomial

### PR DESCRIPTION
**Pull request by stevenndungu**
Not complete, few changes to be updated

### CODE REVIEW

**Comment by stevenndungu** [comment]
Note: Centred radio button not fully implemented yet - Awaiting implementation of passing function within a function in the new system

**Comment by dannyparsons** [comment]
Function within a function has already been done on some dialogs, maybe ask @lilyclements for advice on that, she did it for File New.

**Comment by stevenndungu** [comment]
Ok, let me check on that dialogue (in case of any question I will get to you Lily). Thanks

**Comment by stevenndungu** [comment]
Something strange just happened, the dlgPolynomial.vb file cannot open at all.

**Comment by lilyclements** [comment]
Have you just updated your branch or anything? Or did it just happen suddenly?

**Comment by stevenndungu** [comment]
I really can't trace,  Maxwell tell me it was corrupted. I have tried rebooting, getting latest copy,... The last thing was to  have a new branch.

**Comment by dannyparsons** [comment]
We can check if this can be accessible by cloning the branch in someone else's repo. Leave this open and keep the branch for now.

**Comment by lilyclements** [comment]
It allowed me to make a pull request of the branch in my repo and it worked fine - which is strange!

**Comment by stevenndungu** [comment]
Yeah, the file became available some time later on the branch. I don't know what had happened since i did not do anything to the branch. Its good I reopened the pull request.

**Comment by lilyclements** [comment]
Okay that's strange. Are you working on this branch then? How is it going?

**Comment by lilyclements** [comment]
@stevenndungu can you give an update on how this branch is going?

**Comment by stevenndungu** [comment]
the dialogue had an issue with reading the parameters automatically, due to lack of a unique parameter for for the default radio button. 
`poly(degree=2, raw=TRUE, x=Size)`----default
`poly(x=scale(x=Size, scale=FALSE, center=TRUE), raw=TRUE, degree=2)`
`poly(degree=2, raw=FALSE, x=Size)`
poly has  three parameters, ```degree`,raw` and `x`,  so setting the first radio button to default was not possible.

**Comment by stevekogo** [comment]
@stevenndungu what is happening with this branch? I see there are conflicts which you might have to address.

**Comment by dannyparsons** [comment]
I suggest this isn't urgent to resolve today since there are conflicts and also still issues with the dialog functionality.

**Comment by stevekogo** [comment]
@stevenndungu can you please respond to this.

**Comment by stevenndungu** [comment]
@stevekogo the dialogue is almost complete with a something to be added by Danny on reading of code by the system. Will check with him when he comes

**Comment by dannyparsons** [comment]
This one might be easier to look at once we're together in Maseno.

**Comment by stevenndungu** [comment]
Closing this branch since it could update to the latest version i guess due to the problem it had some time back

**Pull request closed without merging**
