### PR TITLE
Added code to Open SST

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
@rdstern @dannyparsons I have done initial implementation on Open SST dialogue. For now, we can import csv files. Other options are still to be done and I have commented out lots of options upon adapting the dialogue from dlgImport. Have a look at the dialogue, try it out with the data that I am going to send to you then advice on how it should look.

NB: The method import_CPT returns a huge data frame which takes time to write to the grid.

**Comment by dannyparsons** [comment]
I think you have done some changes from what I mentioned in the issue, so is this ready to go in now?

**Comment by stevekogo** [comment]
@dannyparsons I think this is ready to go in. However, we will have to improve the efficiency of the function. ImpImprovements can be done later.

**Comment by dannyparsons** [comment]
That's fine, we can come back to it when we get into the climatic more

**Pull request merged**
