### PR TITLE
Grid syncing, Instat object & File Menu

### PR DESCRIPTION
**Pull request by dannyparsons**
Implemented new syncing method between grids and Instat object and updated some functions on the file menu (some not working and some incomplete)

### CODE REVIEW

**Comment by deaspo** [comment]
Hi Danny, line 43 of clsGridLink.vb is causing the debugging of the project to crash. Something to do with NullReferenceException. Quick discussion on this needed since I cannot run the project.

**Comment by dannyparsons** [comment]
Hi Polycarp,

Sorry only just saw this. It's not crashing for me so I'll have to see it
with you to see what's going on to resolve it. Let's discuss tomorrow, what
were you doing when it crash?

As a temporary fix, you can comment out lines 43-45 and instead just set
those 3 boolean values to True and that should at least get it running
until we see the problem.

Danny

**Comment by deaspo** [comment]
I think its probably because the InstantObject was updated, right? The methods get_data_changed() e.t.c I do not have them.

**Comment by dannyparsons** [comment]
The latest version of the Instat Object is in the static folder which you
have when you pull the repo so it should be using that version and find
those methods.

**Comment by dannyparsons** [comment]
Have you determined why the error is appearing?

I think adding:
        If frmMain.clsRLink.bInstatObjectExists Then

        End If

before line 43 and until the end of this class is needed because it
shouldn't try to update anything without an Instat object. Whether that
fixes your error or not is a different question..

**Pull request merged**
