### PR TITLE
Sdg layer options: small bug fixing in "" method

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**

### CODE REVIEW

**Comment by FrancoisJRenaud** [comment]
@maxwellfundi @lilyclements @stevekogo @Lunalo : this is ready for peer review and testing... It concerns the autofill methods when click return on sdgLayerOptions.
stat = identity in the geom_bar, geom_freqpoly and geom_density cases 
aes x="" for geom_boxplot and dotplot, and
aes x="" and y="" in the geom_point and geom_line cases.

Should now behave coherently depending on if apply on all layers and ignore global aes are ticked. 

Just one bug commented inline: 
'Warning: in some cases, this is sources of errors in R: is a continuous variable is mapped to y (for instance plot1 <- ggplot(diamonds,aes(y=price,x="") + geom_boxplot()), and in some layer where global aes are ignored, "" is mapped to y (e.g. plot1 + geom_point(inherit.aes = FALSE, mapping = aes(x="",y="")) ), then an error occurs as a discrete vriable cannot be mapped to a continuous scale.

**Comment by maxwellfundi** [comment]
@dannyparsons  could you have a look at this too.

**Comment by dannyparsons** [comment]
Has anyone reviewed or tested it?

**Comment by lilyclements** [comment]
I haven't yet, but am about to skype Francois about it so I know more about what to look for. So, I'll review it shortly!

**Comment by FrancoisJRenaud** [comment]
How is this doing @lilyclements ?

**Comment by lilyclements** [comment]
I think this is ready to @dannyparsons to review

**Pull request merged**
