### PR TITLE
Two Way Frequencies

### PR DESCRIPTION
**Pull request by stevenndungu**
In progress- few things to be sorted out.

### CODE REVIEW

**Comment by stevenndungu** [comment]
@dannyparsons I have experienced a challenge with adding the first additional pair in  the controls passing two parameters in this dialogue.
- Though this case is slightly unique; Setting of  for example `Receiver.SetParameterIncludeArgumentName(False)` does not work for the case of the additional pair parameter added.
Apart from that issue the dialogue has taken shape

**Comment by stevenndungu** [comment]
Thanks, understood.

**Comment by stevenndungu** [comment]
@rdstern after discussion with Danny, Lily and Maxwell we have agreed to change the design to;
image
To accommodate for the Both radio button - so that the user can be able to select on both table and graph frequencies options easily.
I don't know if you have different views on the same.

**Comment by stevenndungu** [comment]
Table checked
image 
Graph checked
image
Both checked
image

**Comment by rdstern** [comment]
Exciting.  That is looking very nice - and neat.

My only comment is that the labels could now be clearer, i.e. "Table Frequencies" and "Graph Frequencies"

**Comment by stevenndungu** [comment]
@africanmathsinitiative/developers this is ready for review

**Comment by dannyparsons** [comment]
We have made changes to a large number of files here together so I am going to merge this now so others can work on these files.

**Comment by lilyclements** [comment]
Okay, I'm still reviewing this. I will merge my design changes into the master branch shortly?

**Comment by dannyparsons** [comment]
Ok sorry, yes you can still do a pull request to the master with any changes.

**Comment by lilyclements** [comment]
It's okay, I spoke to Steven and merged them into his branch he's doing Two Way Freq. on

**Pull request merged**
