### PR TITLE
Manage menu

### PR DESCRIPTION
**Pull request by Lunalo**
Editing for okEnabled

### CODE REVIEW

**Comment by dannyparsons** [comment]
Ready to merge?

**Comment by Lunalo** [comment]
Let me make the rest of the changes. I wanted to see your changes. 

So I can just continue and let you know when am done

**Comment by dannyparsons** [comment]
Ok I'll keep it open for now.

**Comment by Lunalo** [comment]
@dannyparsons  you can merge this and I will get your changes as we agreed during lunch.

**Pull request merged**
