### PR TITLE
dlgRugPlot

### PR DESCRIPTION
**Pull request by maxwellfundi**
In progress!

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons  I tried implementing what we discussed yesterday and looks like we are heading in the right path, but, even after updating the parameter with the current value of the current receiver, it passes the value twice. I have showed this @stevekogo  and we think you could have a look now at this.

**Comment by dannyparsons** [comment]
Ok I'll have a look through this and see.

**Comment by maxwellfundi** [comment]
Great. Lots discussions needed for this though after you have a look.

**Comment by dannyparsons** [comment]
looking at this now

**Comment by lilyclements** [comment]
@maxwellfundi I think this branch can be deleted and closed? My understanding is that this is sorted in Danny's branch he merged yesterday

**Pull request closed without merging**
