### PR TITLE
Dlg convert to factor columns frm main vb proj

### PR DESCRIPTION
**Pull request by nyagishira**
there are changes on frmmain and vbproj

### CODE REVIEW

**Comment by dannyparsons** [comment]
Hi Mary, I don't understand some of these changes.
The ConvertTo dialog should be deleted and the ConvertColumnsToFactors dialog should remain (but needs to be renamed ConvertColumns).
But I see you have deleted some of the ConvertTo files, but others have been renamed?
Can we try what we did yesterday where you delete one dialog at a time?

**Comment by nyagishira** [comment]
am redoing it

**Comment by dannyparsons** [comment]
I think this can be closed now?

**Comment by nyagishira** [comment]
yea

**Pull request closed without merging**
