### PR TITLE
Toolbar buttons #2124

### PR DESCRIPTION
**Pull request by FrancoisJRenaud**
So didn't write anything yet but will be editing toolbar buttons...
In progress...

### CODE REVIEW

**Comment by dannyparsons** [comment]
As long as @Lunalo is happy for you to edit frmMain

**Comment by Lunalo** [comment]
Francois, you can go ahead and edit frmMain

**Comment by FrancoisJRenaud** [comment]
Cool thanks ! (sorry didn't know these were on fraim main)

**Comment by dannyparsons** [comment]
Are you doing copy on here too?

**Comment by FrancoisJRenaud** [comment]
yup

**Comment by FrancoisJRenaud** [comment]
oups, last copy should be copy button okok. Ready to merge.

**Pull request merged**
