### PR TITLE
Dlg string handling

### PR DESCRIPTION
**Pull request by shadrackkibet**
@dannyparsons .This is ready for you.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@dannyparsons this is looking good. its a blank dialog that has just controls. Please merge this so that we can get him to work on other bits of the code. 

Thanks

**Comment by dannyparsons** [comment]
What about adding it to the project?

**Comment by maxwellfundi** [comment]
Its now added @dannyparsons . these files had not been commited but he has now sent them.

**Comment by dannyparsons** [comment]
Great. Did you check with @Lunalo that no one is editing frmMain?

**Comment by shadrackkibet** [comment]
yes i checked with him.No one is editing frmMain.

**Pull request merged**
