### PR TITLE
Stevekogo climdex

### PR DESCRIPTION
**Pull request by dannyparsons**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@stevekogo So there was a small bug in the RSyntax so it's good we spotted that, and it's now fixed in here and solves your issue. It's easier that I just merge this and your branch and you continue on a new one if there is more to do still. I also changed back the `ci` parameter in the sub dialog, this needs to be the climdex object function not just the name of it. It still produces the same output but check how it's working now.

**Comment by dannyparsons** [comment]
@rdstern could also be testing this dialog now

**Comment by rdstern** [comment]
Will do, and also the other dialogues that Steve has worked on recently, and supplied data.  All hotting up very well!

**Comment by rdstern** [comment]
Steve, the dialogue seems to work very well - as far as it goes.  Is it finished, in your view, or do you have plans for it to do more?  Some enhancements could be good for 0.2, but others should wait until the dialogue structure has been sorted out.  What are you working on now (if anything?) for this dialogue?

**Comment by stevekogo** [comment]
There are a few defaults that I have implemented but yet to submit then we
can leave it there for now.

On 18 Jan 2017 13:05, "rdstern" <notifications@github.com> wrote:

Steve, the dialogue seems to work very well - as far as it goes. Is it
finished, in your view, or do you have plans for it to do more? Some
enhancements could be good for 0.2, but others should wait until the
dialogue structure has been sorted out. What are you working on now (if
anything?) for this dialogue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/africanmathsinitiative/Instat/pull/2523#issuecomment-273434528>,
or mute the thread

**Pull request merged**
