### PR TITLE
dlgReorder metadata

### PR DESCRIPTION
**Pull request by AlexSananka**

### CODE REVIEW

**Comment by dannyparsons** [comment]
@AlexSananka Great to see you've made a start on GitHub and pull requests.
I hope the team have explained to you the reviewing process that pull requests go through. The first step is for the author to comment when it is ready for review, tagging the developers. 
So this will not get looked at until you say it's ready. If this is all new to you, just ask the team to help explain.

**Comment by AlexSananka** [comment]
@dannyparsons  Thanks for this,Yes they did though am still learning.

**Comment by AlexSananka** [comment]
@africanmathsinitiative/developers This is ready for review

**Comment by lilyclements** [comment]
I know you haven't edited the layout - but while you're on this branch I have a few comments about the layout.
We want the ucrDataFrame to always be at (10,10)
And the label to have a colon as well as move to a height of about 24 so that it's closer to the receiver

The code itself looks really good to me. Once you've made designer changes I'd say it's ready for Danny to look at

**Comment by AlexSananka** [comment]
@lilyclements This is ready for you

**Comment by Lunalo** [comment]
@AlexSananka  @lilyclements 

Great work

**Comment by lilyclements** [comment]
@dannyparsons This is ready for you to review

**Comment by dannyparsons** [comment]
@AlexSananka Good job on your first merged pull request. 

As I have been saying to the rest of the team, it's crucial that you understand the code you're writing. So I think now is a good time for you to pick a dialog that has more controls and will need more code. I would also suggest you select a dialog that is currently working so that you can see how it works before you edit it. You might want to discuss this with the others to find a suitable dialog.
This is a good chance for you to learn how more of the code works, so it's really important that you ask lots of questions as you go along. The more you ask the more you will understand.

**Pull request merged**
