### PR TITLE
fetching latest copy for installer

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Let's wait until Monday again, please. I think Monday might be your new day for the installer, but we will let you know.

**Comment by maxwellfundi** [comment]
Okay, thats is fine. Thank you

**Comment by maxwellfundi** [comment]
@dannyparsons  could this be merged now for the installer?

**Comment by rdstern** [comment]
I would wait until Danny replies.

My inclination is that it isn’t sufficiently different from last week’s version to do another installation at this stage.

Cheers

Roger

**Pull request closed without merging**
