### PR TITLE
Redone unused levels

### PR DESCRIPTION
**Pull request by maxwellfundi**

### CODE REVIEW

**Comment by bethanclarke** [comment]
The code is now working well. I suggest that you test the dialogue thoroughly to see what changes need to be made. Also look at the design of the dialogue and tidy it up. The dialogue needs to be made bigger, so that the grid doesn't get cut off any more.

**Comment by maxwellfundi** [comment]
Okay thanks Beth, WIll do

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by maxwellfundi** [comment]
@dannyparsons  this needs to be merged too. thanks. @bethanclarke  tested it too

**Comment by dannyparsons** [comment]
Great but what happens when you go back into the dialog more than once. Have you tested what happens there?

**Comment by maxwellfundi** [comment]
@dannyparsons i have seen the omission on the load, the above commit fixes it now, it was left out during submission

**Comment by maxwellfundi** [comment]
@dannyparsons  done.

**Pull request merged**
