### PR TITLE
Fixing PCA and CCA dialogues

### PR DESCRIPTION
**Pull request by stevekogo**

### CODE REVIEW

**Comment by stevekogo** [comment]
@dannyparsons I have edited one line in instat_object. The commented line was there before but it was causing the dialogues to crush.

**Comment by dannyparsons** [comment]
If you change the AssignTo to also include the data frame name then you won't have this issue

**Comment by dannyparsons** [comment]
Is this working now?

**Comment by stevekogo** [comment]
@dannyparsons It is now working well.

**Pull request merged**
