### PR TITLE
Import *.Excel files

### PR DESCRIPTION
**Pull request by deaspo**
This is ready for discussion and finalization @rdstern  and @dannyparsons

### CODE REVIEW

**Comment by dannyparsons** [comment]
Great start on this. I haven't look deeply at the code but I have tested the branch. I was able to load an xlsx file into the Instat object, excellent! And the sheets combo box displayed the right sheet names.
However, I found a few things not working well:
- When I selected a file, nothing showed in the gird until I changed the selected sheet. It should load the preview for the selected sheet after selecting a file.
- Once when I ran the code, nrows was still a parameter to readWorkbook so I got an error. This is because I first opened a csv, so the nrows parameter needs to be removed correctly. 

Then I have some design changes to suggest from discuss with Roger:
- All types should be the default selection for the Open File dialog.
- Remove xls as an option since we can't do this.
- The input file preview text box is only for csv or text files so this should be hidden and it shouldn't try to read the file in the xlsx case.
- We would like to be able to import multiple sheets at once. I think readWorkbook can only do one at a time, so we would need to run this multiple times, not sure exactly how to do this yet. We can leave this for now but think about it.

We like the options for xlsx. Roger is looking at the parameters of readWorkbook and he might make some suggestions for the xlsx options on the dialog and what sensible defaults should be.

**Comment by rdstern** [comment]
Hi Polycarp,

This is great.

The main thing I didn’t see is the option to import a named range.  That is the namedRegion argument would be instead of a sheet.  It is a choice when choosing a sheet.  (In Genstat the list of sheets has an “S:” in front, while ranges has an “R:”.  (In Excel a named range is for a workbook as a whole, not a sheet.)
Then the choice of rows and columns is ignored, ideally it would then be greyed out.

I like the omit rows from the top.  Could there also be a “Choose Rows” button and “Choose Columns” as another.  These are what is greyed out when named range is selected.

Cheers

Roger

**Comment by deaspo** [comment]
@dannyparsons I have made the changes, only one more remaining. The one that concerns that you have to select a sheet before previewing it.

**Comment by deaspo** [comment]
Hi @dannyparsons , I have updated the code, still updating. To avoid conflicts, could you please accept  #1178 so that I can work with the import RDS method in this dialog? Mean while your opinion on the code so far are welcomed.

**Comment by deaspo** [comment]
Hi @dannyparsons , would like to finalise discussing this dialog

**Comment by dannyparsons** [comment]
Ok I'll take a look at this.

**Comment by dannyparsons** [comment]
Hi Polycarp, good progress here. A few comments:

- Can you set the defaults for the Import Dataset dialog that none of the groups of controls are visible i.e. csv, RDS. So that until a file is selected, only the File control is visible.
- Also there's a few more checkboxes needed to match all of the parameters from the import_RDS method.
- When I selected an RDS file, it tried to display a preview in the Text box and an empty grid was there. These controls can be hidden in the RDS file case (unless the RDS file is just a dataframe and then the grid preview can be visible).
- When I clicked on From Library radio button in the From Library dialog it crashed

**Comment by deaspo** [comment]
I think this is ready but I have the following points to make:

- The reason the FromLibrary dialog was crashing is because of an earlier bug that I had told you. When we want to deselect the selected item from the combo box, the dialog crashes, cboPackages.selectedIndex = -1 was the cause.

- We will hide the preview for the Text box but the in the future the grid should be able to show the preview of the incoming file. This was from my discussion with @volloholic

**Comment by dannyparsons** [comment]
OK sorry just saw that you have discussed this with David. I can see how the grid could display a preview of the data in RDS file but not sure how you can do anything for the text box.

**Comment by dannyparsons** [comment]
If it's ready for review I'll take another look at how it's working.

**Comment by deaspo** [comment]
It's ready

**Comment by dannyparsons** [comment]
Sorry, haven't been online today. I'll go through it tomorrow morning.

**Comment by dannyparsons** [comment]
This is working really well! I was able to import sheets from RDS, cvs and xlsx all into the same object. And opening RDS files from library links nicely with the Import Dialog. 

A couple of things I did notice:

When you switch between Load from R and Load from Instat collection radio buttons, the list of data sets doesn't load automatically without going back into the combobox. This should be simple to fix, just call load datasets when the radio button Load from R is checked.
The RDS checkbox options don't seem to do anything. Can you link these up with the parameters? Also, there's only 3 checkboxes and I think there should be 6 for the different parameters of import_RDS.

Apart from those small things looks like it's working really well.

**Comment by deaspo** [comment]
Hi @dannyparsons , still getting the same error.

**Comment by dannyparsons** [comment]
Hi Polycarp, the error is caused because the grid link is trying to get the data formatted to the decimal places specified in the variables_metadata. However, in the case where include_metadata = FALSE the variables_metadata is cleared so the column for decimal places doesn't exist. 
To fix this we can add this line below. The update_variables_metadata adds defaults back in for variables_metadata, including decimal places. So when grid link tries to get the formatted data now, there won't be the error finding decimal places
clipboard01

**Comment by deaspo** [comment]
Hi @dannyparsons  made the change, now working

**Pull request merged**
