### PR TITLE
correcting IhelpID

### PR DESCRIPTION
**Pull request by nyagishira**

### CODE REVIEW

**Comment by dannyparsons** [comment]
Are these changes because of the new help file? If so, you should also upload the updated compiled help file to the static folder.

**Comment by nyagishira** [comment]
am checking on dialogs first then i will update the help later

**Comment by dannyparsons** [comment]
Are you checking with the new help or the old help file?

**Comment by nyagishira** [comment]
new help

**Comment by dannyparsons** [comment]
Ok good, then you should upload the new compiled help first or at the same time as this, otherwise those numbers will be wrong until the new help is in place.

**Comment by nyagishira** [comment]
i want to t dialogs first. Maybe you could merge them after i upload the
new help

**Comment by dannyparsons** [comment]
Yep I can do that.

**Pull request merged**
