### PR TITLE
Dlg transpose

### PR DESCRIPTION
**Pull request by lilyclements**
@africanmathsinitiative/instat  This is ready for review

### CODE REVIEW

**Comment by lilyclements** [comment]
This code has been re-updated since the updated dialog setup and added conditions in #2618 so this is ready for review.

**Comment by dannyparsons** [comment]
I've resolved the conflict. Just needs a review from someone now.

**Comment by maxwellfundi** [comment]
image

I get this error when i click okay here @lilyclements .

**Comment by lilyclements** [comment]
What did you put in selector/etc to get that error? Are you using an updated branch too?
let me investigate. This wasn't happening before, but something may have happened when Danny resolved the conflict?

**Comment by lilyclements** [comment]
That's a very good find, so as it transpires this was a bug before changing the code - where if you put in one column to transpose on a dataset with several columns, that error comes up. I never noticed it because the dataset I used to transpose only had one column. I'll write it up as an issue.

**Comment by maxwellfundi** [comment]
Okay great @lilyclements . I guess if this had a problem initially then its ready for @dannyparsons

**Pull request merged**
