### PR TITLE
Dlg add comments

### PR DESCRIPTION
**Pull request by Lunalo**
@dannyparsons 

We now need to add the method for this

### CODE REVIEW

**Comment by dannyparsons** [comment]
Yes, that's right. We don't have it yet, so happy to accept this if someone reviews what's there.

**Comment by lilyclements** [comment]
Is this ready for review?

**Comment by maxwellfundi** [comment]
@dannyparsons  this looks good. It can go in before the method is created. its ready for you.

**Comment by lilyclements** [comment]
I had a few comments I was waiting to make while waiting to be confirmed if this was ready for review. I'm just going to make them here as I feel they should be addressed, even if this is not the final version. Just so it works the same as the previous version.

We need to have the ucrDataFrame to change depending what is selected. This is something I came across in dlgRowNamesOrNumbers. Perhaps have a look at that to see? It also meant we just could have one selector instead of two despite only needing the variables list to show in one instance

Theold version of this code also had that the column was disabled when the rdo was checked.
Additionally, the labels corresponding to them were disabled. Perhaps we should think about adding in a LinkedEnabled (like there is a LinkedDisplay currently) for labels?

The labels were too high for their corresponding receivers, and the top of the first receiver should be aligned with the top of the selector listbox.

**Pull request merged**
