### PR TITLE
Start of rains

### PR DESCRIPTION
**Pull request by lilyclements**

### CODE REVIEW

**Comment by Lunalo** [comment]
@dannyparsons 

I think you should look at this

**Comment by lilyclements** [comment]
So I'm still having a little work on this. It's just with a small issue which I'm not too sure how to fix but think I can work it out!

**Comment by stevekogo** [comment]
@lilyclements Should I help review the code? Is it working so that I can test as well?

**Comment by lilyclements** [comment]
It is working. I need to sort a little bit out to then re-enable the fourth check box but this won't be today. If you were to review it now then that would be great!

**Pull request merged**
