### PR TITLE
dlgChangeType-Organizing the designer

### PR DESCRIPTION
**Pull request by nyagishira**

### CODE REVIEW

**Comment by nyagishira** [comment]
I have a concern,dlgChangeType is noton the frmmain and i don't know where
to put it.again to me it looks similar to dlgConvertTo but am not sure.
kindly advise me

**Comment by dannyparsons** [comment]
Thanks for spotting this. It may be a duplicate dialog. I will discuss with Roger and get back to you.

**Comment by nyagishira** [comment]
okay

**Comment by dannyparsons** [comment]
Yes I think this is an old dialog that is no longer needed. Can you delete it?
It's great that you are checking all the dialogs, and good also that before you make edits on the dialog, see if it's used. If you think a dialog might not be needed you can ask me or Roger.

**Pull request merged**
