### PR TITLE
Translation to spanish

### PR DESCRIPTION
**Pull request by nyagishira**
vbproj,options dialog and a .es.resx spanish resource file to all dialogs

### CODE REVIEW

**Comment by rdstern** [comment]
Great!  Many thanks.  Roger

**Comment by dannyparsons** [comment]
Great to have this done! 
To discuss: whether we include this now, or wait until we have the upgraded Translation Toolkit working.

**Comment by nyagishira** [comment]
OK Danny

**Comment by nyagishira** [comment]
You asked me to do it Roger

**Comment by nyagishira** [comment]
how about vbproj danny

**Comment by dannyparsons** [comment]
We definitely want the Spanish translation quite soon. I discussed with David quickly and we think because the upgrade to the Translation Toolkit is a big change, it will be easier if we don't add any more languages until we have the upgrade working properly with the current languages.
It was still a good task for you to do this and learn how to add a new language because we will need this very soon hopefully!

**Pull request closed without merging**
