### PR TITLE
Dlg color by property

### PR DESCRIPTION
**Pull request by Lunalo**
The two functions for remove and color are sharing two parameters ( properties and data_name) 
It has proven difficult calling these two functions in the dialog. Therefore the dialog is partly working and request for the improvement in the new system to insure its full functionality.

### CODE REVIEW

**Comment by dannyparsons** [comment]
Thanks, will look into this soon.

**Comment by stevekogo** [comment]
@Lunalo Address the conflicts in this pull request.

**Comment by dannyparsons** [comment]
I think I can resolve those conflicts later so just carry on for now.

**Comment by Lunalo** [comment]
@dannyparsons 

I think I need to re implement this too. So, I request you merge this to allow for new implementation

**Pull request merged**
